import {NextResponse} from 'next/server'

export const dynamic='force-dynamic'
import { AMFI_HISTORY as HISTORY, DISCLOSURE_SOURCES as SOURCES, cachedDisclosurePages, cachedHistoryWindow } from '@/lib/amfi-cache'
function parseDate(s:string){const m=s.trim().match(/^(\d{1,2})[-\/]([A-Za-z]{3})[-\/](\d{4})$/);if(!m)return null;const months:any={Jan:0,Feb:1,Mar:2,Apr:3,May:4,Jun:5,Jul:6,Aug:7,Sep:8,Oct:9,Nov:10,Dec:11};if(months[m[2]]===undefined)return null;return new Date(Date.UTC(+m[3],months[m[2]],+m[1]))}
function fmt(d:Date){const m=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];return `${String(d.getUTCDate()).padStart(2,'0')}-${m[d.getUTCMonth()]}-${d.getUTCFullYear()}`}
function parseHistory(text:string,code:string){const out:{nav:number;date:string;time:number}[]=[];for(const raw of text.split(/\r?\n/)){const p=raw.trim().split(';').map(x=>x.trim());if(p.length>=8&&p[0]===code){const nav=Number(p[4]),date=p[7],d=parseDate(date);if(Number.isFinite(nav)&&d)out.push({nav,date,time:d.getTime()})}}return out.sort((a,b)=>a.time-b.time)}
async function historyAround(code:string,target:Date){const from=new Date(target);from.setUTCDate(from.getUTCDate()-7);const to=new Date(target);to.setUTCDate(to.getUTCDate()+7);const url=`${HISTORY}?frmdt=${encodeURIComponent(fmt(from))}&todt=${encodeURIComponent(fmt(to))}`;return parseHistory(await cachedHistoryWindow(url),code)}
function cagr(start:number,end:number,years:number){if(start<=0||end<=0)return null;return (Math.pow(end/start,1/years)-1)*100}
async function fetchDisclosurePage(url:string){ return cachedDisclosurePages().then(x => url===SOURCES.factsheets?x.factsheets:url===SOURCES.riskometer?x.riskometer:x.ter) }
function extractNear(text:string,needle:string,patterns:RegExp[]){const low=text.toLowerCase(), idx=low.indexOf(needle.toLowerCase());if(idx<0)return null;const chunk=text.slice(Math.max(0,idx-1800),Math.min(text.length,idx+2600));for(const re of patterns){const m=chunk.match(re);if(m?.[1])return m[1].replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}return null}
async function disclosureLookup(code:string,name:string,amc:string){const key=(code+' '+name).trim();const out:any={benchmark:null,risk:null,ter:{direct:null,regular:null},sources:SOURCES,coverage:{factsheet:false,riskometer:false,ter:false}};try{const [riskHtml,terHtml,factsHtml]=await Promise.all([fetchDisclosurePage(SOURCES.riskometer),fetchDisclosurePage(SOURCES.ter),fetchDisclosurePage(SOURCES.factsheets)]);const needle=key.toLowerCase();const risk=extractNear(riskHtml,needle,[/Risk[^<]{0,80}<[^>]*>([^<]{3,40})/i,/risk[- ]?o[- ]?meter[^<]{0,120}>([^<]{3,40})/i]);const bench=extractNear(factsHtml,needle,[/Benchmark[^<]{0,100}<[^>]*>([^<]{3,160})/i]);const direct=extractNear(terHtml,needle,[/Direct[^<]{0,100}<[^>]*>([0-9]+(?:\.[0-9]+)?)%?/i]);const regular=extractNear(terHtml,needle,[/Regular[^<]{0,100}<[^>]*>([0-9]+(?:\.[0-9]+)?)%?/i]);if(risk){out.risk=risk;out.coverage.riskometer=true}if(bench){out.benchmark=bench;out.coverage.factsheet=true}if(direct){out.ter.direct=Number(direct);out.coverage.ter=true}if(regular)out.ter.regular=Number(regular)}catch{}return out}

export async function GET(req:Request){const u=new URL(req.url),code=u.searchParams.get('code')||'',name=u.searchParams.get('name')||'',nav=Number(u.searchParams.get('nav')||0);if(!code)return NextResponse.json({status:'error',message:'scheme code required'},{status:400});try{const now=new Date();const latest=await historyAround(code,now);const end=nav>0?nav:latest.at(-1)?.nav;const results:any={5:null,7:null,10:null};if(end){for(const y of [5,7,10]){const target=new Date(now);target.setUTCFullYear(target.getUTCFullYear()-y);const rows=await historyAround(code,target);const start=rows.sort((a,b)=>Math.abs(a.time-target.getTime())-Math.abs(b.time-target.getTime()))[0]?.nav;if(start)results[y]=cagr(start,end,y)}}const disclosure=await disclosureLookup(code,name,u.searchParams.get('amc')||'');return NextResponse.json({status:'live',scheme:{code,name},returns:results,benchmark:disclosure.benchmark,risk:disclosure.risk,ter:disclosure.ter,sources:disclosure.sources,coverage:disclosure.coverage,source:'AMFI historical NAV + AMFI disclosure pages',note:'Long-term CAGR is calculated from the nearest available historical NAV around each anniversary. Disclosure fields are populated only when a scheme match is found on the official AMFI pages.'})}catch(e){return NextResponse.json({status:'unavailable',scheme:{code,name},returns:{5:null,7:null,10:null},benchmark:null,risk:null,ter:{direct:null,regular:null},message:e instanceof Error?e.message:'Analytics unavailable',sources:SOURCES})}}
