'use client'
import {useEffect,useMemo,useState} from 'react'
type Holding={name:string;category:string;invested:number;current:number;sip:number}
type Sip={name:string;amount:number;day:number}
const holdings0:Holding[]=[
{name:'Parag Parikh Flexi Cap Fund',category:'Flexi Cap',invested:520000,current:623000,sip:15000},
{name:'UTI Nifty 50 Index Fund',category:'Large Cap Index',invested:430000,current:501000,sip:15000},
{name:'HDFC Nifty Next 50 Index Fund',category:'Next 50 Index',invested:280000,current:335000,sip:7500},
{name:'Axis India Manufacturing Fund',category:'Thematic',invested:160000,current:171000,sip:5000}]
const sips0:Sip[]=[
{name:'Parag Parikh Flexi Cap Fund',amount:15000,day:5},
{name:'UTI Nifty 50 Index Fund',amount:15000,day:10},
{name:'HDFC Nifty Next 50 Index Fund',amount:7500,day:15},
{name:'Axis India Manufacturing Fund',amount:5000,day:20}]
const funds=[['Parag Parikh Flexi Cap Fund','Flexi Cap','86','18.4%','Moderate'],['HDFC Flexi Cap Fund','Flexi Cap','84','17.6%','Moderate'],['UTI Nifty 50 Index Fund','Index','82','15.7%','Moderate'],['ICICI Prudential Nifty 50 Index Fund','Index','81','15.5%','Moderate'],['HDFC Nifty Next 50 Index Fund','Index','79','17.9%','Moderately High'],['Motilal Oswal Midcap Fund','Mid Cap','78','20.1%','High'],['Nippon India Growth Mid Cap Fund','Mid Cap','77','19.3%','High'],['Mirae Asset Large & Midcap Fund','Large & Mid Cap','76','16.9%','Moderately High'],['SBI Small Cap Fund','Small Cap','75','22.0%','Very High'],['Nippon India Small Cap Fund','Small Cap','74','23.1%','Very High'],['Axis India Manufacturing Fund','Thematic','72','N/A','High'],['Parag Parikh Conservative Hybrid Fund','Hybrid','70','10.8%','Moderately Low']]
const chart=[10.2,10.6,10.4,11.1,11.8,12.4,12.1,13.2,14.1,14,15.3,16.1,17,18.4]
const money=(n:number)=>`₹${Math.round(n).toLocaleString('en-IN')}`

export default function Home(){
 const [active,setActive]=useState('Dashboard'),[period,setPeriod]=useState('1Y'),[liveRec,setLiveRec]=useState<any>(null),[loadingRec,setLoadingRec]=useState(false)
 const [profileOpen,setProfileOpen]=useState(false),[profile,setProfile]=useState({name:'Your name',email:'',mobile:'',photo:''}),[liveFunds,setLiveFunds]=useState<any[]>([]),[fundStatus,setFundStatus]=useState('Loading live AMFI data…'),[fundSearch,setFundSearch]=useState('')
 const [holdings,setHoldings]=useState(holdings0),[sips,setSips]=useState(sips0)
 const [amount,setAmount]=useState(50000),[phone,setPhone]=useState(''),[saved,setSaved]=useState(false)
 const totals=useMemo(()=>{let i=0,c=0;holdings.forEach(h=>{i+=h.invested;c+=h.current});return {i,c,g:c-i,p:(c-i)/i*100}},[holdings])
 const allocation=useMemo(()=>[
 ['Parag Parikh Flexi Cap Fund',Math.round(amount*.4),'Core diversified'],
 ['UTI Nifty 50 Index Fund',Math.round(amount*.3),'Low-cost core'],
 ['HDFC Nifty Next 50 Index Fund',Math.round(amount*.15),'Higher-growth core'],
 ['Axis India Manufacturing Fund',Math.round(amount*.1),'Theme, capped'],
 ['Cash / short-term reserve',Math.round(amount*.05),'Dry powder']] as [string,number,string][],[amount])
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem('rvs-profile')||'null');if(p)setProfile(p)}catch{}},[])
 useEffect(()=>{localStorage.setItem('rvs-profile',JSON.stringify(profile))},[profile])
 useEffect(()=>{const t=setTimeout(()=>{const q=encodeURIComponent(fundSearch.trim());fetch(`/api/funds?limit=200${q?`&q=${q}`:''}`).then(r=>r.json()).then(d=>{setLiveFunds(d.funds||[]);setFundStatus(d.status==='live'?`Live AMFI NAV · ${d.count} matching schemes · ${d.asOfLabel}`:'AMFI connection unavailable — showing fallback data')}).catch(()=>setFundStatus('AMFI connection unavailable — showing fallback data'))},300);return()=>clearTimeout(t)},[fundSearch])
 const filteredFunds=liveFunds
 const today=new Date().getDate()
 const next=useMemo(()=>sips.map(s=>({...s,days:s.day>=today?s.day-today:s.day+30-today})).sort((a,b)=>a.days-b.days)[0],[sips])
 async function getLiveRecommendation(){
   setLoadingRec(true)
   try{
     const r=await fetch('/api/recommendation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount,risk:'Moderate'})})
     const data=await r.json()
     setLiveRec(data)
   }finally{setLoadingRec(false)}
 }
 function accept(){setSips(s=>{const m=new Map(s.map(x=>[x.name,x]));allocation.filter(x=>x[0].includes('Fund')).forEach(x=>m.set(x[0],{name:x[0],amount:x[1],day:m.get(x[0])?.day||5}));return [...m.values()]});setSaved(true)}
 return <main>
 <aside className="sidebar"><div className="brand"><span>RVS</span><div><b>RVS WealthPilot</b><small>AI investing copilot</small></div></div>
 {['Dashboard','Invest This Month','AI Fund Manager','My SIPs','SIP Planner','Fund Research','Market Intelligence'].map(x=><button className={active===x?'nav active':'nav'} onClick={()=>setActive(x)} key={x}>{x}</button>)}
 <div className="bottom">V13 · Public Beta</div></aside>
 <section className="content"><header><div><label>SEPTEMBER 2026</label><h1>{active}</h1><span className="v6tag">V13 · Public Beta · Live AMFI NAV</span></div><div className="accountWrap"><button className="profile" onClick={()=>setProfileOpen(v=>!v)}>{profile.photo?<img src={profile.photo} alt="Profile"/>:(profile.name||"RVS").split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase()}</button>{profileOpen&&<AccountPanel profile={profile} setProfile={setProfile} onClose={()=>setProfileOpen(false)}/>}</div></header>

 <div className="betaBanner"><span className="betaDot">●</span><div><b>RVS WealthPilot · Public Beta</b><small>Early-access build. Portfolio figures are demo data until you add your own holdings. Mutual-fund NAV search is sourced server-side from AMFI.</small></div><span className="betaTag">BETA</span></div>

 <div className="disclaimerBanner"><div className="disclaimerIcon">⚠️</div><div><b>AI-created investing companion — not financial advice</b><p>WealthPilot helps make investment analysis easier to understand. Before investing, verify the latest NAV, fund performance, risk level and market trend on the actual/official investment platform.</p></div></div>

 {active==='Dashboard'&&<><div className="hero card"><div><span className="pill green">● AI view: Continue SIP</span><h2>Your portfolio is healthy.</h2><p>You're up <b>{totals.p.toFixed(1)}%</b>. The manager is prioritising diversified funds and controlled thematic exposure.</p></div><div className="health"><small>Portfolio health</small><strong>82</strong><span>/100</span></div></div>
 <div className="grid4"><Metric l="Portfolio value" v={money(totals.c)} d={`+${money(totals.g)} gain`}/><Metric l="Invested" v={money(totals.i)} d={`${totals.p.toFixed(1)}% return`}/><Metric l="Monthly SIP" v={money(sips.reduce((a,s)=>a+s.amount,0))} d="Active"/><Metric l="Risk" v="Moderate" d="32 / 100"/></div>
 <div className="liveStrip"><div><span>DATA STATUS</span><b>Live NAV + portfolio engine</b><small>Validated data connector · production setup pending</small></div><div><span>ENGINE</span><b>RVS WealthPilot V12</b><small>Portfolio health + XIRR + allocation</small></div><div><span>REMINDERS</span><b>3-day SIP workflow</b><small>SMS/WhatsApp provider required</small></div></div>
 <div className="cols"><div className="card"><div className="head"><div><h3>Portfolio performance</h3><p>Interactive illustrative history.</p></div><div className="periods">{['1M','6M','1Y','3Y','5Y'].map(p=><button className={period===p?'sel':''} onClick={()=>setPeriod(p)} key={p}>{p}</button>)}</div></div><Chart/></div>
 <div className="card"><h3>Next SIP</h3><p>Keep sufficient balance ready before your investment date.</p>{next&&<div className="next"><b>{next.name}</b><strong>{money(next.amount)}</strong><small>{next.days===0?'Due today':`Due in ${next.days} days`} · {next.day}th</small></div>}<button className="primary full" onClick={()=>setActive('My SIPs')}>Manage SIP reminders</button></div></div>
 <div className="cols"><div className="card"><h3>How your funds are performing</h3><p>Current value, gain and portfolio weight.</p>{holdings.map(h=>{let g=h.current-h.invested,p=g/h.invested*100,w=h.current/totals.c*100;return <div className="holding" key={h.name}><div><b>{h.name}</b><small>{h.category} · {w.toFixed(1)}% weight</small></div><div className={g>=0?'gain':'loss'}>{g>=0?'+':''}{money(g)}<small>{g>=0?'+':''}{p.toFixed(1)}%</small></div><i style={{width:`${Math.min(w*3,100)}%`}}/></div>})}</div>
 <div className="card"><h3>AI monthly recommendation</h3><p>Suggested deployment if you have ₹50K.</p>{allocation.slice(0,4).map(x=><div className="alloc" key={x[0]}><span>{x[0]}<small>{x[2]}</small></span><b>{money(x[1])}</b><i style={{width:`${x[1]/amount*100}%`}}/></div>)}<button className="primary full" onClick={()=>setActive('Invest This Month')}>Open monthly decision →</button></div></div></>}

 {active==='Invest This Month'&&<><div className="card big"><span className="pill green">Personalised monthly decision</span><h2>I have money to invest this month</h2><p>Enter the amount and get a ranked allocation based on your saved portfolio and risk rules.</p><div className="amount"><label>Amount available</label><div>₹<input type="number" value={amount} onChange={e=>setAmount(Math.max(0,Number(e.target.value)))}/></div></div>
 <div className="recHero"><div><small>Recommended deployment</small><strong>{money(amount)}</strong><p>Moderate risk · 5–10 year horizon · diversified first</p></div><span className="pill">82% confidence</span></div>
 <div className="recList">{allocation.map((x,i)=><div className="recRow" key={x[0]}><em>{i+1}</em><div><b>{x[0]}</b><small>{x[2]}</small></div><strong>{money(x[1])}</strong><span className={i===3?'watch':'add'}>{i===3?'WATCH':'ADD'}</span></div>)}</div>
 <div className="card innerCard"><div className="head"><div><h3>More funds to research</h3><p>These are alternatives from the research universe. They are not automatically recommended.</p></div><button className="secondary" onClick={()=>setActive('Fund Research')}>See all 12 →</button></div><div className="miniFundGrid">{funds.slice(0,8).map(f=><div className="miniFund" key={f[0]}><span className="pill">{f[1]}</span><b>{f[0]}</b><small>{f[4]} risk · illustrative score {f[2]}/100</small></div>)}</div></div>
 <div className="reason"><b>Manager rationale</b><br/>Prioritise diversified core funds, add growth exposure, and cap the thematic allocation. V4 separates data ingestion, quantitative scoring, risk rules and AI explanation. Live recommendations are enabled only after current NAV/benchmark/fund data is available.</div>
 <div className="audit"><b>Decision audit trail</b><span>Data freshness: <strong>{fundStatus.includes('Live AMFI')?'Live AMFI NAV':'Fallback data'}</strong></span><span>Risk rule: <strong>Moderate / diversified</strong></span><span>Concentration guard: <strong>Thematic ≤ 10%</strong></span><span>Recommendation: <strong>Illustrative</strong></span></div>
 <button className="secondary" onClick={getLiveRecommendation}>{loadingRec?"Analysing…":"Analyse with V7 engine"}</button> <button className="primary bigbtn" onClick={accept}>{saved?'✓ Recommendation saved to My SIPs':'Accept recommendation'}</button></div>
 {liveRec&&<div className="liveResult"><div><b>V7 quantitative result</b><span>{liveRec.dataStatus}</span></div>{liveRec.allocation?.map((x:any)=><div className="liveRow" key={x.fund}><span><b>{x.fund}</b><small>{x.reason}</small></span><strong>{money(x.amount)}</strong><em>{x.score}/100</em></div>)}</div>}
 </>}

 {active==='AI Fund Manager' &&<div className="card big"><span className="pill green">RVS WealthPilot</span><h2>Ask your fund manager</h2><p>Use this space for portfolio-performance questions and monthly investment decisions. The production AI will connect to your live holdings and market intelligence.</p><div className="bubble"><b>AI Fund Manager</b><br/>Your portfolio is currently <strong>+{totals.p.toFixed(1)}%</strong>. Default action: <strong>Continue SIP</strong>. Review funds that persistently trail their benchmark or peers after adjusting for risk.</div><div className="suggestions"><button onClick={()=>setActive('Dashboard')}>Why is my portfolio up/down?</button><button onClick={()=>setActive('Dashboard')}>Which fund is underperforming?</button><button onClick={()=>setActive('Fund Research')}>Compare funds side-by-side</button><button onClick={()=>setActive('SIP Planner')}>Should I increase my SIP?</button><button onClick={()=>setActive('Invest This Month')}>What should I invest this month?</button></div></div>}

 {active==='My SIPs'&&<div className="card big"><div className="head"><div><h2>My SIPs & reminders</h2><p>Every SIP, its amount and next payment date.</p></div><span className={saved?'pill green':'pill'}>{saved?'● Reminder setup available':'Reminder not configured'}</span></div><div className="siplist">{sips.map(s=><div className="siprow" key={s.name}><div><b>{s.name}</b><small>Monthly · {s.day}th</small></div><strong>{money(s.amount)}</strong><span className="pill green">Active</span></div>)}</div>
 <div className="reminder"><h3>3-day mobile reminder</h3><p>Enter your number. In production, the scheduler will send an SMS/WhatsApp notification three days before each SIP.</p><div><input placeholder="+91 98XXXXXXXX" value={phone} onChange={e=>setPhone(e.target.value)}/><button className="primary" onClick={()=>setSaved(!!phone)}>Enable reminders</button></div>{saved&&phone&&<small className="success">✓ Reminder preference saved for {phone}. Actual SMS/WhatsApp delivery needs a connected messaging provider.</small>}</div>
 <div className="preview">🔔 <div><b>Notification preview</b><p>"Your ₹15,000 SIP is due in 3 days. Please ensure sufficient balance in your account."</p></div></div></div>}

 {active==='SIP Planner'&&<div className="card big"><h2>SIP Planner</h2><p>Adjust your monthly SIP and see the suggested allocation.</p><input className="range" type="range" min="10000" max="200000" step="5000" value={amount} onChange={e=>setAmount(Number(e.target.value))}/><div className="bigmoney">{money(amount)} <small>/ month</small></div>{allocation.map(x=><div className="alloc" key={x[0]}><span>{x[0]}<small>{x[2]}</small></span><b>{money(x[1])}</b><i style={{width:`${x[1]/amount*100}%`}}/></div>)}</div>}

 {active==='Fund Research'&&<div className="card big"><div className="head"><div><span className="pill green">V7 data layer</span><h2>Fund Research</h2><p>NAV, returns, benchmark gap, risk and cost in one view.</p></div><button className="secondary" onClick={()=>location.reload()}>Refresh data</button></div><div className="researchNote">{fundStatus}. Live NAV is sourced server-side from AMFI. Returns, risk and scoring are shown only when validated data is available; WealthPilot does not treat NAV alone as a recommendation.</div><div className="researchToolbar"><input placeholder="Search fund, AMC or category…" value={fundSearch} onChange={e=>setFundSearch(e.target.value)}/><span>{filteredFunds.length} schemes returned</span></div><div className="fundgrid">{filteredFunds.slice(0,60).map(f=><div className="fund" key={f.code}><span className="pill">{f.category||'Mutual Fund'}</span><h3>{f.name}</h3><p><b>{f.amc}</b><br/>Scheme code: <b>{f.code}</b><br/>NAV: <b>₹{Number(f.nav).toLocaleString('en-IN')}</b><br/>NAV date: <b>{f.navDate}</b><br/>ISIN: <b>{f.isin||'Not available'}</b></p><button className="secondary" onClick={()=>setActive('Invest This Month')}>Use in analysis</button></div>)}</div><div className="sourceNote">Primary live source: AMFI latest NAV feed. AMFI also provides NAV history; historical NAV requests are limited to 90 days per request, so longer-period analytics should be built as controlled backfills. citeturn1search2</div></div>}

 {active==='Market Intelligence'&&<div className="card big"><h2>Market Intelligence</h2><p>The V7 engine is designed to combine official mutual-fund NAV data, fund performance, benchmark comparison, portfolio/risk data, macro signals and news before generating a recommendation.</p><div className="signals">{['NAV & history · AMFI latest and historical NAV','Fund performance · returns, drawdown and consistency','Benchmark · scheme vs benchmark performance','Portfolio · overlap, sector weights and concentration','Risk · volatility, downside and Risk-o-meter','Macro/news · rates, inflation, earnings and policy'].map(x=><div key={x}><span>●</span><b>{x}</b></div>)}</div>
 <div className="sourceNote">V4 data-source design: AMFI NAV/NAV history is the primary mutual-fund data input; SEBI risk disclosures and benchmark comparisons are part of the risk layer.</div></div>}
 </section></main>
}
function AccountPanel({profile,setProfile,onClose}:{profile:any;setProfile:any;onClose:()=>void}){const file=(e:any)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>setProfile((p:any)=>({...p,photo:String(r.result)}));r.readAsDataURL(f)};return <div className="accountPanel"><div className="accountHead"><div><b>Account details</b><small>Your WealthPilot profile</small></div><button onClick={onClose}>×</button></div><div className="avatarEdit">{profile.photo?<img src={profile.photo} alt="Profile"/>:<div className="avatarFallback">{(profile.name||"RVS").split(" ").map((x:string)=>x[0]).join("").slice(0,2).toUpperCase()}</div>}<label className="uploadBtn">Change photo<input type="file" accept="image/*" onChange={file}/></label></div><label>Name<input value={profile.name} onChange={e=>setProfile((p:any)=>({...p,name:e.target.value}))}/></label><label>Email<input type="email" value={profile.email} onChange={e=>setProfile((p:any)=>({...p,email:e.target.value}))}/></label><label>Mobile<input inputMode="tel" value={profile.mobile} onChange={e=>setProfile((p:any)=>({...p,mobile:e.target.value}))}/></label><button className="primary full" onClick={onClose}>Save profile</button></div>}
function Metric(p:{l:string;v:string;d:string}){return <div className="card metric"><small>{p.l}</small><strong>{p.v}</strong><em>{p.d}</em></div>}
function Chart(){let min=Math.min(...chart),max=Math.max(...chart);let pts=chart.map((v,i)=>`${i/(chart.length-1)*100},${90-(v-min)/(max-min)*75}`).join(' ');return <div className="chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={pts} fill="none" stroke="currentColor" strokeWidth="1.8" vectorEffect="non-scaling-stroke"/></svg><div><span>12 mo ago</span><span>6 mo ago</span><span>Now</span></div></div>}
